<?php

define("DEBUG", false);

define("ADMIN_USERNAME", "DEFAULT_ADMIN_USERNAME");
define("ADMIN_PASSWORD", "DEFAULT_ADMIN_PASSWORD");
define("ADMIN_EMAIL", "DEFAULT_ADMIN_EMAIL");

define("WEB_TITLE", "DEFAULT_WEB_TITLE");
define("WEB_ROOT", "DEFAULT_WEB_ROOT");
define("WEB_DESCRIPTION", "DEFAULT_WEB_DESCRIPTION");

define("DB_HOST", "DEFAULT_DB_HOST");
define("DB_USERNAME", "DEFAULT_DB_USERNAME");
define("DB_PASSWORD", "DEFAULT_DB_PASSWORD");
define("DB_NAME", "DEFAULT_DB_NAME");
